In [48]:
print("Assignment 1")

Assignment 1


In [49]:
import pandas as pd
df = pd.read_csv("Corona_NLP_Train.csv", encoding="latin1")
df.sample(5)

UserName  ScreenName                      Location     TweetAt  \
32064     35863       80815  Los Angeles / Ventura County  07-04-2020   
2399       6198       51150          North Charleston, SC  17-03-2020   
27898     31697       76649                          #USA  04-04-2020   
31017     34816       79768  Wellington City, New Zealand  06-04-2020   
34738     38537       83489        Whangarei, New Zealand  08-04-2020   

                                           OriginalTweet Sentiment  
32064  Whoa! Hadn't heard about this until now.\r\r\n...  Negative  
2399   SC CORONAVIRUS UPDATE | If you've been out &am...  Positive  
27898  I just gave away 6000 of other people s money ...  Negative  
31017  Kaikohe locals queue for covid 19 testing afte...  Positive  
34738  Covid 19 coronavirus: Hundreds request virus c...  Positive

In [147]:
class_labels = df["Sentiment"].unique()
print(class_labels)
print(len(df["Sentiment"].unique()))

['Neutral' 'Positive' 'Extremely Negative' 'Negative' 'Extremely Positive']
5


In [153]:
label_to_index = {}
index_to_label = {}

for i, label in enumerate(class_labels):
    label_to_index[label] = i
    index_to_label[i] = label

print(label_to_index["Extremely Negative"])
print(index_to_label[2])

2
Extremely Negative


In [148]:
tweets = list(df["OriginalTweet"][:100])
# print(tweets[0:5])
vocab= set(" ".join(tweets).split())
print(vocab)
print(len(vocab))

{'challenging', '#nohandsanitizer', '2019,', 'resulted', 'several', 'store,', 'after', 'freezer', 'themselves.', 'anyone', 'deem', 'but', 'die', 'entire', "They're", 'news', 'employer', 'got', 'took', 'Thank', '(at', 'weÂ\x92ve', 'attendees,', 'advantage', '&amp;', 'https://t.co/PnA797jDKV', 'off', 'my', 'morning', 'actions', 'My', 'necessities', '#CoronaVirusUpdates', 'shut', 'misinformed', 'mean', 'safty', 'ensues', 'whatever', 'trolleys', 'objected', '#manila', 'leave.', "Didn't", 'An', 'feel', 'these', '#totallockdown', 'BE', 'provide', 'still', "General's", 'restaurants,', '@SenatorRomney', 'things', 'supplies,', 'form', 'sound', 'health', 'find', '@Tim_Dodson', '4-12', 'redrawn', 'https://t.co/cfXch7a2lU', 'store.', 'he', 'fact', 'for', 'result', 'cleaning', 'systems', 'watchdog', 'retail&amp;a', 'put', 'normal!', 'sometimes', 'this,', 'https://t.co/3hCd9IiWoX', 'looked', 'lol', 'capitalizing', 'easy.', '#Liverpool', 'https://t.co/dCSXHUj3U0', '#bestiptv', 'Worried', '??', 'just'

In [149]:
token_to_word = {}
word_to_token = {}
for i, word in enumerate(vocab):
    token_to_word[i]=word
    word_to_token[word]=i

print(word_to_token["several"])


4


In [150]:
sample_input = tweets[88]
print(sample_input)

Please don't hoard food and water. There's absolutely no need to panic buy; the supply chain is completely interrupted. And above all, please don't hoard sanitizing products; there are people out there who really need them, probably more than you. #DontPanicBuy #coronavirus


In [151]:
tokenized_input = []
for word in sample_input.split():
    tokenized_input.append(word_to_token[word])


print(tokenized_input)
while len(tokenized_input)<50:
    tokenized_input.append(0)

print(tokenized_input)
tokenized_input = np.array(tokenized_input).reshape(-1,1)
print(tokenized_input.shape)

[1567, 293, 1141, 1085, 1220, 285, 415, 1218, 1461, 658, 603, 560, 1433, 768, 1082, 371, 851, 853, 402, 1571, 367, 393, 259, 293, 1141, 1540, 278, 513, 800, 1325, 980, 513, 652, 1568, 658, 106, 873, 1385, 1267, 1305, 832, 452]
[1567, 293, 1141, 1085, 1220, 285, 415, 1218, 1461, 658, 603, 560, 1433, 768, 1082, 371, 851, 853, 402, 1571, 367, 393, 259, 293, 1141, 1540, 278, 513, 800, 1325, 980, 513, 652, 1568, 658, 106, 873, 1385, 1267, 1305, 832, 452, 0, 0, 0, 0, 0, 0, 0, 0]
(50, 1)


In [152]:
reconstructed_input = []
tokenized_list_input = tokenized_input.flatten().tolist()
# print(tokenized_list_input)
for token in tokenized_list_input:
    reconstructed_input.append(token_to_word[token])

reconstructed_input = " ".join(reconstructed_input)
print(reconstructed_input)


Please don't hoard food and water. There's absolutely no need to panic buy; the supply chain is completely interrupted. And above all, please don't hoard sanitizing products; there are people out there who really need them, probably more than you. #DontPanicBuy #coronavirus challenging challenging challenging challenging challenging challenging challenging challenging


In [110]:
print(tokenized_input.shape)

(50, 1)


In [111]:
input_dim = 50
hidden_dim = 50
output_dim = 5

1. h0 (init 0)
2. for i in range(len_input):
3. $h_i$ = $tanh(W*inputEmbedding + U*h_{i-1})$
4. y = tanh(V*h1)

In [112]:
import numpy as np
W = np.random.rand(hidden_dim, input_dim)
U = np.random.rand(hidden_dim, hidden_dim)
V = np.random.rand(output_dim, hidden_dim)
print(W)
print(W.shape)

[[0.2477219  0.56088804 0.2294584  ... 0.97798683 0.05999492 0.77490627]
 [0.28783237 0.29851048 0.70043653 ... 0.80917525 0.06637459 0.56640805]
 [0.72777089 0.19971296 0.55748764 ... 0.76240091 0.47685784 0.23391781]
 ...
 [0.95672741 0.27685078 0.46049392 ... 0.25786418 0.52374716 0.43249829]
 [0.30017212 0.85438438 0.59811774 ... 0.24418652 0.72106694 0.48809714]
 [0.95127098 0.34629157 0.73388608 ... 0.110792   0.26911229 0.76245162]]
(50, 50)


In [113]:
def activation_fn(x):
    return np.maximum(0,x)

In [114]:
print(tokenized_input.shape)
print(W.shape)

(50, 1)
(50, 50)


In [116]:
h1 = activation_fn(W@tokenized_input)
print(h1)
np.shape(h1)

[[14803.23424206]
 [18181.1171005 ]
 [19325.31034023]
 [21757.23764413]
 [16041.26277987]
 [19785.29978655]
 [17399.05778636]
 [21630.66287055]
 [17860.41515219]
 [19357.26497123]
 [17712.13446535]
 [16703.54963972]
 [18020.28392919]
 [20361.72355336]
 [14387.12521511]
 [18823.42191155]
 [14817.40958827]
 [18074.57238141]
 [19796.01898248]
 [21525.46744195]
 [17060.27308461]
 [16879.22439678]
 [17095.33118772]
 [18047.28969923]
 [17405.44303607]
 [19309.85665089]
 [20214.52378502]
 [17703.7305956 ]
 [12225.65102972]
 [17062.69573009]
 [16260.5220199 ]
 [19592.77227586]
 [16027.86013308]
 [17932.45034862]
 [19329.13748521]
 [17280.391125  ]
 [15946.22716145]
 [19778.17059999]
 [17409.33706074]
 [16387.6440207 ]
 [18393.99052693]
 [17033.1264692 ]
 [19310.77905142]
 [18962.99433364]
 [18258.48322031]
 [20138.19517077]
 [19341.27415841]
 [16855.97048578]
 [17519.35456828]
 [20900.4257829 ]]


(50, 1)

In [117]:
print(V.shape)

(5, 50)


In [125]:
y1 = activation_fn(V@h1)
print(y1)

[[426946.81043085]
 [471860.59028371]
 [410871.24545725]
 [454743.86729878]
 [471506.26168746]]


In [141]:
list_output = np.array(y1.flatten().tolist())
scaled_arr = list_output / np.mean(list_output)
print(scaled_arr)

[0.95474153 1.05517804 0.91879323 1.0169015  1.05438569]


In [142]:
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [144]:
class_probs = sigmoid(scaled_arr)
print(class_probs)

[0.72206774 0.74176799 0.71479615 0.73436861 0.74161618]


In [146]:
max_value_index = class_probs.tolist().index(max(class_probs))
print(max_value_index)

1


In [156]:
output_class = index_to_label[max_value_index]
print(output_class)

Positive


# Transformer

## Input

In [1]:
import pandas as pd
df = pd.read_csv("Corona_NLP_Train.csv", encoding="latin1")
df.sample(5)

UserName  ScreenName                    Location     TweetAt  \
9514      13313       58265  Email: richard@coilpod.com  20-03-2020   
1295       5094       50046                         NaN  17-03-2020   
24163     27962       72914                New York, NY  26-03-2020   
22002     25801       70753                         NaN  25-03-2020   
10475     14274       59226                         NaN  20-03-2020   

                                           OriginalTweet           Sentiment  
9514   #Restaurants in these #coronavirus times can s...  Extremely Negative  
1295   @Reuters #COVID2019 Stock up now! \r\r\n   You...  Extremely Negative  
24163  Lysol Laundry Sanitizer Additive Crisp Linen -...             Neutral  
22002  Interesting. The sub-saharan story is incomple...            Positive  
10475                       This is absolutely THE ONE               Neutral

In [2]:
class_labels = df["Sentiment"].unique()
print(class_labels)
print(len(df["Sentiment"].unique()))

['Neutral' 'Positive' 'Extremely Negative' 'Negative' 'Extremely Positive']
5


In [3]:
label_to_index = {}
index_to_label = {}

for i, label in enumerate(class_labels):
    label_to_index[label] = i
    index_to_label[i] = label

print(label_to_index["Extremely Negative"])
print(index_to_label[2])

2
Extremely Negative


In [24]:
import re
import random

tweets = list(df["OriginalTweet"])
cleaned_tweets = [re.sub(r'[^A-Za-z0-9 ]+', '', tweet) for tweet in tweets]
# print(cleaned_tweets[100:110])
# print(tweets[0:5])
vocab= set(" ".join(cleaned_tweets).split())
filtered_vocab = {word for word in vocab if word.islower() and word.isalpha()}
print(random.sample(filtered_vocab,3))
print(len(filtered_vocab))

['rubles', 'propertyprices', 'congregate']
35441


C:\Users\rohit\AppData\Local\Temp\ipykernel_12968\2528759162.py:10: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  print(random.sample(filtered_vocab,3))


## Tokenization

In [42]:
token_to_word = {}
word_to_token = {}
for i, word in enumerate(filtered_vocab):
    token_to_word[i]=word
    word_to_token[word]=i

token_to_word[-1]=""
word_to_token[""]=-1
print(word_to_token["several"])

26666


In [43]:
sample_input = tweets[101]
print(sample_input)
sample_input = list(sample_input.split())
sample_input = [word.lower() for word in sample_input if word.isalpha()]
print(sample_input)

Rapid delivery food order made (since no slots elsewhere for weeks). All seemed fine until email listing what was out of stock. They are about to deliver...one bottle of orange juice! #coronavirus #panicbuying #whatashitshow
['rapid', 'delivery', 'food', 'order', 'made', 'no', 'slots', 'elsewhere', 'for', 'all', 'seemed', 'fine', 'until', 'email', 'listing', 'what', 'was', 'out', 'of', 'they', 'are', 'about', 'to', 'bottle', 'of', 'orange']


In [44]:
import numpy as np
tokenized_input = []
for word in sample_input:
    tokenized_input.append(word_to_token[word])


print(tokenized_input)
while len(tokenized_input)<50:
    tokenized_input.append(-1)

print(tokenized_input)
tokenized_input = np.array(tokenized_input).reshape(-1,1)
print(tokenized_input.shape)

[34288, 29586, 32267, 8209, 9123, 12143, 34732, 1008, 3889, 6094, 460, 3792, 21853, 4040, 5546, 29832, 15932, 19885, 785, 3598, 21879, 27637, 18298, 11082, 785, 13249]
[34288, 29586, 32267, 8209, 9123, 12143, 34732, 1008, 3889, 6094, 460, 3792, 21853, 4040, 5546, 29832, 15932, 19885, 785, 3598, 21879, 27637, 18298, 11082, 785, 13249, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
(50, 1)


In [45]:
reconstructed_input = []
tokenized_list_input = tokenized_input.flatten().tolist()
# print(tokenized_list_input)
for token in tokenized_list_input:
    reconstructed_input.append(token_to_word[token])

reconstructed_input = " ".join(reconstructed_input)
print(reconstructed_input)


rapid delivery food order made no slots elsewhere for all seemed fine until email listing what was out of they are about to bottle of orange                        


## Embedding + Positional Embedding

## Attention (Key, Query, Value dot products)

In [46]:
print(tokenized_input)
print(tokenized_input.shape)

[[34288]
 [29586]
 [32267]
 [ 8209]
 [ 9123]
 [12143]
 [34732]
 [ 1008]
 [ 3889]
 [ 6094]
 [  460]
 [ 3792]
 [21853]
 [ 4040]
 [ 5546]
 [29832]
 [15932]
 [19885]
 [  785]
 [ 3598]
 [21879]
 [27637]
 [18298]
 [11082]
 [  785]
 [13249]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]
 [   -1]]
(50, 1)


## Add and Norm

## Feed Forward

## Add and Norm

## Linear

## Softmax